sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PIP=pip

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env:
        - TOXENV=py36
        - PIP=pip3

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      $PIP install tox
    fi
  - $PIP install cython
  - $PIP install tox-travis

script: tox
