sudo: false
language: python
python:
  - "2.7"
env:
  - PIP=pip

matrix:
  include:
    - os: linux
    - os: osx
      language: generic
      env:
        - TOXENV=py27
        - PIP=pip2

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      $PIP install tox
    fi
  - $PIP install cython
  - $PIP install tox-travis

script: tox
