sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: true
    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.5
        - TOXENV=py37

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      pyenv install $PYTHON_VERSION
    fi
  - pip install cython
  - pip install tox-travis

script: tox
